# -*- coding: utf-8 -*-
"""sentence-embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgtFZ-jpcHhlKEYlcWTxbvTj1NCc2qnU
"""

# Install first (if needed):
# pip install sentence-transformers numpy

from sentence_transformers import SentenceTransformer
import numpy as np

# Sample list of 5 sentences (like Wikipedia-style text)
sentences = [
    "The Eiffel Tower is located in Paris and is one of the most famous landmarks in the world.",
    "Photosynthesis is the process by which green plants convert sunlight into chemical energy.",
    "The Amazon rainforest is the largest tropical rainforest on Earth.",
    "Albert Einstein developed the theory of relativity.",
    "The Pacific Ocean is the largest and deepest ocean on Earth."
]

# Load pre-trained embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
embeddings = model.encode(sentences)

# Convert to numpy array (optional)
embeddings = np.array(embeddings)

# Print results
print("Number of sentences:", len(sentences))
print("Embedding shape:", embeddings.shape)  # (5, 384)

print("\nSample embedding for first sentence:\n")
print(embeddings[0])

# Save embeddings to file
np.save("embeddings.npy", embeddings)

print("\nEmbeddings saved to embeddings.npy")